# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'
variables:
  build_name: RWODevOpsTest
  git_hash: null

steps:
- script: sudo apt-get install libboost-all-dev
  displayName: 'Installing dependencies for the project DevOpsTest'
  
- script: g++ -std=c++11 -I/usr/include/boost/asio -I/usr/include/boost -o binary.out main.cpp connection.cpp connection_manager.cpp mime_types.cpp reply.cpp request_handler.cpp request_parser.cpp server.cpp -lboost_system -lboost_thread -lpthread
  displayName: 'Compiling the project DevOpsTest'

- script: echo $(Build.BuildID)
  displayName: 'Printing the build ID of the project'
- script: echo $(build_name) 
  displayName: 'Displaying the pipeline variable'
- script: 
    echo $(git log --format="%H" -n 1 | head -c 7)
    echo '##vso[task.setvariable variable=git_hash]$(git log --format="%H" -n 1 | head -c 7)'
    echo $(git_hash)
  displayName: 'Printing the git_hash variables'


- script: 
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
